### PR TITLE
Add support stdin for hook

### LINKED ISSUE #12: Add support stdin for hook
Some hooks of git pass in extra data through stdin, these parameters are very useful for hook scripts, so we need to support it.

> https://git-scm.com/docs/githooks/2.32.0

Hook list for supported stdin data:

- [pre-receive](https://git-scm.com/docs/githooks/2.32.0#pre-receive)
  - `<old-value> SP <new-value> SP <ref-name> LF`
- [reference-transaction](https://git-scm.com/docs/githooks/2.32.0#_reference_transaction)
  - `<old-value> SP <new-value> SP <ref-name> LF`
- [post-rewrite](https://git-scm.com/docs/githooks/2.32.0#_post_rewrite)
  - `<old-object-name> SP <new-object-name> [ SP <extra-info> ] LF`
- [pre-push](https://git-scm.com/docs/githooks/2.32.0#_pre_push)
  - `<local ref> SP <local object name> SP <remote ref> SP <remote object name> LF`

### PR DESCRIPTION
**Pull request by binsee**
Fixes #12

### CODE REVIEW

**Comment by binsee** [comment]
Demonstrate the effect with a pre-push example:

```bash
> git push             
args: [
  "origin",
  "git@github.com:binsee/sidecar.git",
  "refs/heads/test2",
  "65b8bd5bd8e8c889fb8ec6228cfada35164cc423",
  "refs/heads/test2",
  "0000000000000000000000000000000000000000"
]
error: failed to push some refs to 'git@github.com:binsee/sidecar.git'

> git push origin      
args: [
  "origin",
  "git@github.com:binsee/sidecar.git",
  "refs/heads/test2",
  "65b8bd5bd8e8c889fb8ec6228cfada35164cc423",
  "refs/heads/test2",
  "0000000000000000000000000000000000000000"
]
error: failed to push some refs to 'git@github.com:binsee/sidecar.git'

> git push origin test2
args: [
  "origin",
  "git@github.com:binsee/sidecar.git",
  "refs/heads/test2",
  "65b8bd5bd8e8c889fb8ec6228cfada35164cc423",
  "refs/heads/test2",
  "0000000000000000000000000000000000000000"
]
error: failed to push some refs to 'git@github.com:binsee/sidecar.git'

> git push origin :test 
args: [
  "origin",
  "git@github.com:binsee/sidecar.git",
  "(delete)",
  "0000000000000000000000000000000000000000",
  "refs/heads/test",
  "65b8bd5bd8e8c889fb8ec6228cfada35164cc423"
]
error: failed to push some refs to 'git@github.com:binsee/sidecar.git'
```

**Review by huan — CHANGES_REQUESTED** [review]
Great work, thank you very much for the improvement!

Could you please bump the minor version to an odd version, so that we can merge this PR and publish a new version on NPM?

Appreciate it!

**Comment by binsee** [comment]
> 

done

**Review by huan — APPROVED** [review]
Awesome, thank you very much for this PR!

**Pull request merged**
